# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='phonenumber_otp',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersignup',
            name='phonenumber_verified',
            field=models.BooleanField(default=False),
        ),
    ]
