# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-11 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_auto_20181111_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='phonenumber_otp',
            field=models.IntegerField(null=True),
        ),
    ]
